ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    publish_tf: true

    # Trust wheel odometry for X and Yaw velocity to provide an initial guess for ICP.
    odom0: /odom_can
    odom0_config: [false, false, false,
                   false, false, false,
                   true, false, false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # Trust Laser Odometry for velocity (X, Y, Yaw). This is immune to slip and sway.
    odom1: /odom_laser
    odom1_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    # Trust VIO (Camera IMU + Stereo) for instant YAW velocity to eliminate map skew.
    odom2: /oak/vio/odometry_fixed
    odom2_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom2_queue_size: 10
    odom2_differential: false
    odom2_relative: false
